// <auto-generated />
using System;
using CarteiraBank.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarteiraBank.Infra.Data.Migrations
{
    [DbContext(typeof(CarteiraBankContext))]
    [Migration("20260420190237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarteiraBank.Domain.Models.Acordo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("agreements", (string)null);
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Boleto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinhaDigitavel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ParcelaAcordoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParcelaAcordoId")
                        .IsUnique();

                    b.ToTable("billets", (string)null);
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorPrincipal")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NumeroContrato")
                        .IsUnique();

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Parcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorJuros")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorMulta")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("installments", (string)null);
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.ParcelaAcordo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcordoId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AcordoId");

                    b.ToTable("agreement_installments", (string)null);
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.SolicitacaoCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecididoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("IdSupervisorDecisor")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoDecisao")
                        .HasColumnType("text");

                    b.Property<int>("QuantidadeParcelasSolicitada")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("credit_applications", (string)null);
                });

            modelBuilder.Entity("CarteiraBank.Infra.Data.Context.EventStoreSqlData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("User")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("stored_events", (string)null);
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Acordo", b =>
                {
                    b.HasOne("CarteiraBank.Domain.Models.Contrato", "Contrato")
                        .WithMany("Acordos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Boleto", b =>
                {
                    b.HasOne("CarteiraBank.Domain.Models.ParcelaAcordo", "ParcelaAcordo")
                        .WithOne("Boleto")
                        .HasForeignKey("CarteiraBank.Domain.Models.Boleto", "ParcelaAcordoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelaAcordo");
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Contrato", b =>
                {
                    b.HasOne("CarteiraBank.Domain.Models.Cliente", "Cliente")
                        .WithMany("Contratos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Parcela", b =>
                {
                    b.HasOne("CarteiraBank.Domain.Models.Contrato", "Contrato")
                        .WithMany("Parcelas")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.ParcelaAcordo", b =>
                {
                    b.HasOne("CarteiraBank.Domain.Models.Acordo", "Acordo")
                        .WithMany("Parcelas")
                        .HasForeignKey("AcordoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acordo");
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.SolicitacaoCredito", b =>
                {
                    b.HasOne("CarteiraBank.Domain.Models.Cliente", "Cliente")
                        .WithMany("SolicitacoesCredito")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Acordo", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Cliente", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("SolicitacoesCredito");
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.Contrato", b =>
                {
                    b.Navigation("Acordos");

                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("CarteiraBank.Domain.Models.ParcelaAcordo", b =>
                {
                    b.Navigation("Boleto");
                });
#pragma warning restore 612, 618
        }
    }
}
